name: Relatórios - TESTE

on:
  workflow_dispatch:   
     inputs:
      branch:
        description: 'master'
        required: true
        default: 'master'
 
jobs:
  build:  
    runs-on: ubuntu-latest    
    steps:    
    - name: Checkout
      uses: actions/checkout@v2
      
    - uses: azure/docker-login@v1
      with: 
        login-server: ghcr.io
        username: ${{ secrets.GH_PACKAGES_USER }}
        password: ${{ secrets.GH_PACKAGES_TOKEN }}
        
    - run: |
        docker build -t ghcr.io/Elitonperoni/webcarros/webcarros:latest -f Dockerfile .
        docker tag ghcr.io/Elitonperoni/webcarros/webcarros:latest ghcr.io/Elitonperoni/webcarros/webcarros:${GITHUB_SHA}
        
    - run: |
        docker push ghcr.io/Elitonperoni/webcarros/webcarros:latest 
        docker push ghcr.io/Elitonperoni/webcarros/webcarros:${GITHUB_SHA} 

# 5. Conectar-se ao servidor via SSH e fazer as operações no servidor
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          # Pare o container atual
          cd /var/docker/webcarros
          docker-compose down

          # Remova a imagem antiga
          docker rmi ghcr.io/Elitonperoni/webcarros/webcarros:latest || true                  
          
          # Suba o container com a nova imagem
          docker-compose up -d
